-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;
CREATE DATABASE ecommerce_db;
USE ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;
DROP TABLE IF EXISTS productTag;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS category;
